CREATE TABLE ESTUDANTE(
	id NUMBER NOT NULL,
	nome VARCHAR2(200) NOT NULL,
	data_nascimento DATE NOT NULL,
	nr_matricula NUMBER NOT NULL UNIQUE,
	ativo CHAR(1) CHECK(ativo IN('S','N')),
	PRIMARY KEY (id)
)

CREATE SEQUENCE SEQ_ESTUDANTE
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

CREATE SEQUENCE SEQ_MATRICULA
 START WITH     2000
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;



INSERT INTO VEM_SER.ESTUDANTE
(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'Diogo',TO_DATE('06-10-2004','dd-mm-yyyy'),SEQ_MATRICULA.NEXTVAL, 'S');

INSERT INTO VEM_SER.ESTUDANTE
(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'Breno',TO_DATE('09-12-2000','dd-mm-yyyy'),SEQ_MATRICULA.NEXTVAL, 'S');

INSERT INTO VEM_SER.ESTUDANTE
(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'Andre',TO_DATE('06-10-2004','dd-mm-yyyy'),SEQ_MATRICULA.NEXTVAL, 'N');

INSERT INTO VEM_SER.ESTUDANTE
(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'Joao',TO_DATE('03-10-2004','dd-mm-yyyy'),SEQ_MATRICULA.NEXTVAL, 'S');

INSERT INTO VEM_SER.ESTUDANTE
(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'Lucas',TO_DATE('12-03-1999','dd-mm-yyyy'),SEQ_MATRICULA.NEXTVAL, 'N');

INSERT INTO VEM_SER.ESTUDANTE
(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'Augusto',TO_DATE('18-7-2005','dd-mm-yyyy'),SEQ_MATRICULA.NEXTVAL, 'S');

INSERT INTO VEM_SER.ESTUDANTE
(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'Iuri',TO_DATE('28-11-2004','dd-mm-yyyy'),SEQ_MATRICULA.NEXTVAL, 'N');

INSERT INTO VEM_SER.ESTUDANTE
(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'Cayo',TO_DATE('12-10-2000','dd-mm-yyyy'),SEQ_MATRICULA.NEXTVAL, 'S');

INSERT INTO VEM_SER.ESTUDANTE
(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'Kalil',TO_DATE('04-10-1999','dd-mm-yyyy'),SEQ_MATRICULA.NEXTVAL, 'N');

INSERT INTO VEM_SER.ESTUDANTE
(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'Pedro',TO_DATE('24-10-2004','dd-mm-yyyy'),SEQ_MATRICULA.NEXTVAL, 'S');

SELECT * FROM ESTUDANTE 