CREATE TABLE PAIS(
	ID_PAIS NUMBER(38,0) NOT NULL,
	NOME VARCHAR2(50) NOT NULL,
	CONSTRAINT PK_PAIS PRIMARY KEY(ID_PAIS)
);

CREATE TABLE ESTADO(
	ID_ESTADO NUMBER(38,0) NOT NULL,
	ID_PAIS NUMBER(38,0) NOT NULL,
	NOME VARCHAR2(50) NOT NULL,
	CONSTRAINT PK_ESTADO PRIMARY KEY(ID_ESTADO),
	CONSTRAINT FK_ESTADO_PAIS FOREIGN KEY (ID_PAIS) REFERENCES PAIS(ID_PAIS)
);

CREATE TABLE CIDADE(
	ID_CIDADE NUMBER(38,0) NOT NULL,
	ID_ESTADO NUMBER(38,0) NOT NULL,
	NOME VARCHAR2(50) NOT NULL,
	CONSTRAINT PK_CIDADE PRIMARY KEY(ID_CIDADE,ID_ESTADO),
	CONSTRAINT FK_CIDADE_ESTADO FOREIGN KEY(ID_ESTADO) REFERENCES ESTADO(ID_ESTADO)
);

CREATE TABLE BAIRRO(
	ID_BAIRRO NUMBER(38,0) NOT NULL,
	ID_CIDADE NUMBER(38,0) NOT NULL,
	ID_ESTADO NUMBER(38,0) NOT NULL,
	NOME VARCHAR2(50) NOT NULL,
	CONSTRAINT PK_BAIRRO PRIMARY KEY (ID_BAIRRO,ID_CIDADE),
	CONSTRAINT FK_ESTADO FOREIGN KEY(ID_CIDADE,ID_ESTADO) REFERENCES CIDADE(ID_CIDADE,ID_ESTADO)
);

CREATE TABLE ENDERECO(
	ID_ENDERECO NUMBER(38,0) NOT NULL,
	ID_BAIRRO NUMBER(38,0) NOT NULL,
	ID_CIDADE NUMBER(38,0) NOT NULL,
	LOGRADOURO VARCHAR2(255) NOT NULL,
	NUMERO NUMBER(38,0) NOT NULL,
	COMPLEMENTO VARCHAR2(100),
	CEP CHAR(9),
	CONSTRAINT PK_ENDERECO PRIMARY KEY(ID_ENDERECO),
	CONSTRAINT FK_BAIRRO FOREIGN KEY (ID_BAIRRO, ID_CIDADE) REFERENCES BAIRRO(ID_BAIRRO,ID_CIDADE)
);


CREATE SEQUENCE SEQ_ENDERECO
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;

CREATE SEQUENCE SEQ_ESTADO
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;

CREATE SEQUENCE SEQ_BAIRRO
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;

CREATE SEQUENCE SEQ_CIDADE
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;

CREATE SEQUENCE SEQ_PAIS
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;

INSERT INTO VEM_SER.PAIS
(ID_PAIS, NOME)
VALUES(SEQ_PAIS.NEXTVAL, 'Brasil');

INSERT INTO VEM_SER.PAIS
(ID_PAIS, NOME)
VALUES(SEQ_PAIS.NEXTVAL, 'Argentina');

INSERT INTO VEM_SER.ESTADO
(ID_ESTADO, ID_PAIS, NOME)
VALUES(SEQ_ESTADO.NEXTVAL, 1, 'Paraíba');

INSERT INTO VEM_SER.ESTADO
(ID_ESTADO, ID_PAIS, NOME)
VALUES(SEQ_ESTADO.NEXTVAL, 1, 'Pernambuco');

INSERT INTO VEM_SER.ESTADO
(ID_ESTADO, ID_PAIS, NOME)
VALUES(SEQ_ESTADO.NEXTVAL, 1, 'Sergipe');

INSERT INTO VEM_SER.ESTADO
(ID_ESTADO, ID_PAIS, NOME)
VALUES(SEQ_ESTADO.NEXTVAL, 1, 'Rio Grande Do Norte');

INSERT INTO VEM_SER.ESTADO
(ID_ESTADO, ID_PAIS, NOME)
VALUES(SEQ_ESTADO.NEXTVAL, 2, 'Cordoba');

INSERT INTO VEM_SER.ESTADO
(ID_ESTADO, ID_PAIS, NOME)
VALUES(SEQ_ESTADO.NEXTVAL, 2, 'Chaco');

INSERT INTO VEM_SER.ESTADO
(ID_ESTADO, ID_PAIS, NOME)
VALUES(SEQ_ESTADO.NEXTVAL, 2, 'San Luis');

INSERT INTO VEM_SER.ESTADO
(ID_ESTADO, ID_PAIS, NOME)
VALUES(SEQ_ESTADO.NEXTVAL, 2, 'Chubut');

INSERT INTO VEM_SER.CIDADE
(ID_CIDADE, ID_ESTADO, NOME)
VALUES(SEQ_CIDADE.NEXTVAL, 1, 'João Pessoa');

INSERT INTO VEM_SER.CIDADE
(ID_CIDADE, ID_ESTADO, NOME)
VALUES(SEQ_CIDADE.NEXTVAL, 1, 'Campina Grande');

INSERT INTO VEM_SER.CIDADE
(ID_CIDADE, ID_ESTADO, NOME)
VALUES(SEQ_CIDADE.NEXTVAL, 2, 'Buenos Aires');

INSERT INTO VEM_SER.BAIRRO
(ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
VALUES(1, 1, 1, 'Manaíra');

INSERT INTO VEM_SER.BAIRRO
(ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
VALUES(2, 2, 2, 'La Union');

INSERT INTO VEM_SER.ENDERECO
(ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES(SEQ_ENDERECO.NEXTVAL, 2, 2, 'Rua 01', 93, 'ap 101', '58398-031');

INSERT INTO VEM_SER.ENDERECO
(ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES(SEQ_ENDERECO.NEXTVAL, 1, 1, 'Rua 02', 91, 'ap 301', '59032-320');

INSERT INTO VEM_SER.ENDERECO
(ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES(SEQ_ENDERECO.NEXTVAL, 2, 2, 'Avenida 02', 92, 'ap 401', '59332-331');


INSERT INTO BAIRRO (ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
VALUES (SEQ_BAIRRO.NEXTVAL, 1, 1, 'Manaíra');


INSERT INTO VEM_SER.BAIRRO
(ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
VALUES(SEQ_BAIRRO.NEXTVAL, 2, 2, 'Santa Cruz');


SELECT * FROM PAIS
SELECT * FROM ESTADO
SELECT * FROM CIDADE
SELECT * FROM ENDERECO 
SELECT * FROM BAIRRO


--Item 1
SELECT NOME FROM PAIS ORDER BY NOME DESC;

--Item 2
SELECT LOGRADOURO,CEP FROM ENDERECO WHERE LOGRADOURO LIKE '%A%'

--Item 3
SELECT * FROM ENDERECO WHERE TRIM(CEP) LIKE '%0'

--Item 4
SELECT * FROM ENDERECO WHERE NUMERO BETWEEN 1 AND 100

--Item 5
SELECT * FROM ENDERECO WHERE LOGRADOURO LIKE 'Rua%' ORDER BY CEP DESC

--Item 6
SELECT COUNT(*) ENDERECOS FROM ENDERECO

--Item 7
SELECT COUNT(*) CIDADES FROM ENDERECO GROUP BY ID_CIDADE 

--Exercicio.1
UPDATE ENDERECO SET LOGRADOURO = 'Rua 03' WHERE ID_ENDERECO = 4 
SELECT * FROM ENDERECO

UPDATE ENDERECO SET LOGRADOURO = 'Rua 04' WHERE ID_ENDERECO = 5 
SELECT * FROM ENDERECO  

--Exercicio.2
UPDATE ENDERECO SET NUMERO = 999999 WHERE ID_ENDERECO = 4
SELECT * FROM ENDERECO  

--Exercicio.3
DELETE FROM ENDERECO
WHERE ID_ENDERECO = (SELECT MAX(ID_ENDERECO) FROM ENDERECO)

--Exercicio.4
DELETE FROM ENDERECO WHERE NUMERO = 999999
SELECT * FROM ENDERECO

--Exercicio.5
DELETE FROM ENDERECO WHERE ID_ENDERECO = 8
DELETE FROM ENDERECO WHERE ID_ENDERECO = 9
SELECT * FROM ENDERECO 
