--RIGHT JOIN 1
SELECT p.NOME,p.DATA_NASCIMENTO,p.CPF, c.NUMERO FROM PESSOA p RIGHT JOIN CONTATO c ON (p.ID_PESSOA = c.ID_PESSOA) 

--RIGHT JOIN 2
SELECT p.NOME,p.CPF,p.DATA_NASCIMENTO, ep.ESTADO,ep.CIDADE,ep.LOGRADOURO,ep.NUMERO,ep.COMPLEMENTO,ep.CEP FROM PESSOA p RIGHT JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (p.ID_PESSOA = PXPE.ID_PESSOA) 
	RIGHT JOIN ENDERECO_PESSOA ep ON (PXPE.ID_ENDERECO = ep.ID_ENDERECO)

-- RIGHT JOIN 3
SELECT p.NOME,p.CPF,p.DATA_NASCIMENTO, ep.TIPO,ep.LOGRADOURO,ep.NUMERO,ep.COMPLEMENTO,ep.CEP,ep.CIDADE,ep.ESTADO,ep.PAIS,c.TIPO,c.NUMERO,c.DESCRICAO FROM PESSOA p RIGHT JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (p.ID_PESSOA = PXPE.ID_PESSOA) 
	RIGHT JOIN ENDERECO_PESSOA ep ON (PXPE.ID_ENDERECO = EP.ID_ENDERECO) RIGHT JOIN CONTATO c ON (p.ID_PESSOA = c.ID_PESSOA)

	
--FULL JOIN 1
SELECT 	p.NOME ,c.NUMERO  FROM PESSOA p FULL JOIN CONTATO c ON (p.ID_PESSOA = c.ID_PESSOA) 

--FULL JOIN 2
SELECT p.NOME,p.CPF ,p.DATA_NASCIMENTO,ep.ESTADO,ep.CIDADE,ep.LOGRADOURO,ep.NUMERO,ep.COMPLEMENTO,ep.CEP FROM PESSOA p FULL JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (p.ID_PESSOA = PXPE.ID_PESSOA) 
	FULL JOIN ENDERECO_PESSOA ep ON (PXPE.ID_ENDERECO = ep.ID_ENDERECO)
	
--FULL JOIN 3
SELECT p.NOME,p.CPF,p.DATA_NASCIMENTO ,ep.TIPO,ep.LOGRADOURO,ep.NUMERO,ep.COMPLEMENTO,ep.CEP,ep.CIDADE,ep.ESTADO,ep.PAIS,c.TIPO,c.NUMERO,c.DESCRICAO FROM PESSOA p FULL JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (p.ID_PESSOA = PXPE.ID_PESSOA) 
	FULL JOIN ENDERECO_PESSOA ep ON (PXPE.ID_ENDERECO = EP.ID_ENDERECO) FULL JOIN CONTATO c ON (p.ID_PESSOA = c.ID_PESSOA)	

	
--EXISTS 1
SELECT * FROM PESSOA p WHERE EXISTS (SELECT * FROM ENDERECO_PESSOA ep) 

--UNION
SELECT p.ID_PESSOA , p.nome, ep.ID_ENDERECO , ep.LOGRADOURO 
FROM pessoa	p JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (p.ID_PESSOA = PXPE.ID_PESSOA) JOIN ENDERECO_PESSOA ep ON (PXPE.ID_ENDERECO = ep.ID_ENDERECO)


 
